version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a"
  - dependency-name: "@types/react"
    versions:
    - ">= 17.a"
