name: Build and publish dev version

on:
  push:
    tags:
      - v1.*-beta.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      if: ${{ success() }}
      run: yarn build
    - name: Install lftp
      if: ${{ success() }}
      run: sudo apt-get update && sudo apt-get install --yes lftp
    - name: Publish
      if: ${{ success() }}
      shell: bash
      env:
        LFTP_USER: ${{ secrets.lftpUser }}
        LFTP_PASSWORD: ${{ secrets.lftpPassword }}
        LFTP_SITE: ${{ secrets.lftpSite }}
      run: |
        lftp -e "set ssl:check-hostname false; open --user $LFTP_USER --env-password $LFTP_SITE && mirror --verbose --reverse --delete --exclude=.htaccess build code; exit"
